
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CMD_ABASTECER CMD_AJUDA CMD_LISTAR CMD_MOEDA CMD_REMOVER CMD_SAIR CMD_SELECIONAR CODIGO MOEDA NOME PRICE QUANTIDADE\n    comando : ajuda\n            | listar\n            | moeda\n            | selecionar\n            | abastecer\n            | remover\n            | sair\n    \n    ajuda : CMD_AJUDA\n    \n    listar : CMD_LISTAR\n    \n    moeda : CMD_MOEDA list_moedas '.'\n    \n    list_moedas : MOEDA\n                | list_moedas ',' MOEDA\n    \n    selecionar : CMD_SELECIONAR CODIGO\n    \n    abastecer : CMD_ABASTECER CODIGO QUANTIDADE\n              | CMD_ABASTECER CODIGO NOME QUANTIDADE PRICE\n    \n    remover : CMD_REMOVER CODIGO\n    \n    sair : CMD_SAIR\n    "
    
_lr_action_items = {'CMD_AJUDA':([0,],[9,]),'CMD_LISTAR':([0,],[10,]),'CMD_MOEDA':([0,],[11,]),'CMD_SELECIONAR':([0,],[12,]),'CMD_ABASTECER':([0,],[13,]),'CMD_REMOVER':([0,],[14,]),'CMD_SAIR':([0,],[15,]),'$end':([1,2,3,4,5,6,7,8,9,10,15,18,20,21,23,27,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-17,-13,-16,-10,-14,-15,]),'MOEDA':([11,22,],[17,25,]),'CODIGO':([12,13,14,],[18,19,20,]),'.':([16,17,25,],[21,-11,-12,]),',':([16,17,25,],[22,-11,-12,]),'QUANTIDADE':([19,24,],[23,26,]),'NOME':([19,],[24,]),'PRICE':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'ajuda':([0,],[2,]),'listar':([0,],[3,]),'moeda':([0,],[4,]),'selecionar':([0,],[5,]),'abastecer':([0,],[6,]),'remover':([0,],[7,]),'sair':([0,],[8,]),'list_moedas':([11,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> ajuda','comando',1,'p_comando','main.py',131),
  ('comando -> listar','comando',1,'p_comando','main.py',132),
  ('comando -> moeda','comando',1,'p_comando','main.py',133),
  ('comando -> selecionar','comando',1,'p_comando','main.py',134),
  ('comando -> abastecer','comando',1,'p_comando','main.py',135),
  ('comando -> remover','comando',1,'p_comando','main.py',136),
  ('comando -> sair','comando',1,'p_comando','main.py',137),
  ('ajuda -> CMD_AJUDA','ajuda',1,'p_ajuda','main.py',143),
  ('listar -> CMD_LISTAR','listar',1,'p_listar','main.py',161),
  ('moeda -> CMD_MOEDA list_moedas .','moeda',3,'p_moeda','main.py',176),
  ('list_moedas -> MOEDA','list_moedas',1,'p_listar_moedas','main.py',185),
  ('list_moedas -> list_moedas , MOEDA','list_moedas',3,'p_listar_moedas','main.py',186),
  ('selecionar -> CMD_SELECIONAR CODIGO','selecionar',2,'p_selecionar','main.py',196),
  ('abastecer -> CMD_ABASTECER CODIGO QUANTIDADE','abastecer',3,'p_abastecer','main.py',223),
  ('abastecer -> CMD_ABASTECER CODIGO NOME QUANTIDADE PRICE','abastecer',5,'p_abastecer','main.py',224),
  ('remover -> CMD_REMOVER CODIGO','remover',2,'p_remover','main.py',252),
  ('sair -> CMD_SAIR','sair',1,'p_sair','main.py',265),
]
