
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER\n    expression : expression '+' term\n               | expression '-' term\n               | term\n    \n    term : term '*' factor\n         | term '/' factor\n         | factor\n    \n    factor : NUMBER\n           | '(' expression ')'\n    "
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'(':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-3,-6,-7,-1,-2,-4,-5,-8,]),'+':([1,2,3,4,10,11,12,13,14,15,],[6,-3,-6,-7,6,-1,-2,-4,-5,-8,]),'-':([1,2,3,4,10,11,12,13,14,15,],[7,-3,-6,-7,7,-1,-2,-4,-5,-8,]),')':([2,3,4,10,11,12,13,14,15,],[-3,-6,-7,15,-1,-2,-4,-5,-8,]),'*':([2,3,4,11,12,13,14,15,],[8,-6,-7,8,8,-4,-5,-8,]),'/':([2,3,4,11,12,13,14,15,],[9,-6,-7,9,9,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression + term','expression',3,'p_expression','main.py',39),
  ('expression -> expression - term','expression',3,'p_expression','main.py',40),
  ('expression -> term','expression',1,'p_expression','main.py',41),
  ('term -> term * factor','term',3,'p_term','main.py',53),
  ('term -> term / factor','term',3,'p_term','main.py',54),
  ('term -> factor','term',1,'p_term','main.py',55),
  ('factor -> NUMBER','factor',1,'p_factor','main.py',67),
  ('factor -> ( expression )','factor',3,'p_factor','main.py',68),
]
